CBV_fb_clone/apps/api_urls/urls.py
from django.urls import path,include
from api_views.views import *
from rest_framework import routers

router = routers.DefaultRouter()
router.register('',UserModelViewSet,basename='register')
    # path('register/', RegisterListCreateAPIView.as_view()),
    # path('register/<int:pk>/', RegisterRetrieveUpdateDestroyAPIView.as_view()),

# in swagger we have doc of this api's
# swagger 
# http://127.0.0.1:8000/post/docs/?format=openapi
urlpatterns = [
    path('register/',include(router.urls)),
    
    path('login/', LoginApiView.as_view()),
    path('logout/', LogoutApiView.as_view()),
    path('profile/', ProfileApiView.as_view()),
    
    path('passChange/', PasswordChangeApiView.as_view()),
    path('post/', PostCreateAPIView.as_view(), name= 'post'),
    path('allpost/',AllPostAPIView.as_view()),
    path('postcrud/<int:pk>/',PostRetrieveUpdateDestroyAPIView.as_view()),
    
    path('like/<int:pk>/',LikeAPIView.as_view()),
    
    path('commets/<int:post_id>/',CommentsAPIView.as_view()),
    
]

CBV_fb_clone/apps/post/urls.py
from django.urls import path
from .views import *

app_name = "Post"
urlpatterns = [

    path('post/', PostFormView.as_view(), name= 'post'),
    path('all_user_post/', all_user_post.as_view(), name= 'all_user_post'),
    path('view_post/', view_post.as_view(), name= 'view_post'),
    path('update_post/<int:pk>/', update_post.as_view(), name= 'update_post'),
    path('delete_post/<int:pk>/', delete_post.as_view(), name= 'delete_post'),
    path('post_detail/<int:pk>/', post_detail.as_view(), name= 'post_detail'),
    path('update_comment/', update_on_comment.as_view(), name='update_on_comment'),

    path('delete_comment/', delete_comment.as_view(), name='delete_comment'),
    
    path('post/comment/<int:pk>/', comment_on_post.as_view(), name='comment_on_post'),
    path('post/like/<int:pk>/', like.as_view() , name= 'like'),
]

CBV_fb_clone/apps/register/urls.py
from django.urls import path
from .views import *

app_name = "Register"
urlpatterns = [
    path('register/', register.as_view(), name='register'),
    path('profile/', profile.as_view(), name='profile'),
]
    # path('', user_login.as_view(), name='user_login'),

    # path('user_logout/', user_logout.as_view(), name='user_logout'),

CBV_fb_clone/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from CBV_fb_clone.apps import *
# import django.contrib.auth.urls
from CBV_fb_clone.apps import api_urls


from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
# def trigger_error(request):
#     division_by_zero = 1 / 0

    # path('sentry-debug/', trigger_error),



from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from django.conf import settings

schema_view = get_schema_view(
    openapi.Info(
        title="FB clone api",
        default_version='v1',),
    public=True,
    # permission_classes=(permissions.AllowAny,),
)
# swagger 
# https://episyche.com/blog/how-to-create-django-api-documentation-using-swagger
# http://127.0.0.1:8000/post/docs/?format=openapi


app_name = "Post"

# from django.contrib.auth.urls
urlpatterns = [
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0),name='schema-swagger-ui'),

    path('admin/', admin.site.urls),
    path('post/',include('post.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('register.urls')),
    
    path('api/',include('api_urls.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CBV_fb_clone/apps/post/models.py
from django.db import models
from django.conf import settings

class UserPost(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='user_post')
    location = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    like = models.IntegerField(default=0)
    cap = models.TextField(verbose_name='Caption')
    desc = models.TextField(verbose_name='Description')
    
    def __str__(self):
        return f"{self.user.first_name}, {self.cap}"
    
    class Meta:
        ordering = ['-created_at']
    
class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(UserPost, on_delete=models.CASCADE, related_name='post_like')
    
    def __str__(self):
        return f"{self.user}, {self.post.user.username}"

class UserComments(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(UserPost, on_delete=models.CASCADE, related_name='post')
    comment = models.TextField(blank=True,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Logged in user: {self.user.first_name}, Comment:  {self.comment}"



from django.dispatch import receiver 
from django.db.models.signals import pre_save,post_save,pre_delete,post_delete
import datetime

@receiver(pre_save,sender = UserPost)
def UserPost_pre_save(sender,instance,**kwargs):
    current_time = datetime.datetime.now()
    with open("logdata.txt", 'a') as file:
        file.write(str(current_time) + '\t' + instance.user.username + ' ' + 'Post created: (pre_save function)'+"\n")
    print('pre_save : post created!')

@receiver(post_save,sender = UserPost)
def UserPost_post_save(sender,instance,**kwargs):
    current_time = datetime.datetime.now()
    with open("logdata.txt", 'a') as file:
        file.write(str(current_time) + '\t' + instance.user.username + ' ' + 'Post created: (post_save function)'+"\n")
    print('post_save : post created!')

CBV_fb_clone/apps/register/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

gen = (
    ("Female", "Female"),
    ("Male", "Male"),
    ("Trans", "Trans"),
    ("Custom", "Custom"),
)

class CustomUser(AbstractUser):
    mobile = models.CharField(max_length=60)
    DOB = models.DateField(auto_now_add=False, blank=True, null=True)
    gender = models.CharField(max_length=60, choices=gen)

    def __str__(self):
        return self.username

#===============Signal's===========================================
from django.dispatch import receiver 
from django.db.models.signals import post_save
import datetime
from django.contrib.auth.signals import user_logged_out,user_logged_in


@receiver(post_save, sender=CustomUser)
def user_pre_save_api(sender, instance, created, **kwargs):
    current_time = datetime.datetime.now()
    if created:  # Only execute for newly created instances
        with open("logdata.txt", "a") as file:
            file.write(str(current_time) + "\t" + instance.username + " " + "User created successfully" + "\n")
    else:
        with open("logdata.txt", "a") as file:
            file.write(str(current_time) + "\t" + instance.username + " " + "Some changes in Database." + "\n")

@receiver(user_logged_in)
def user_login(sender, request, **kwargs):
    current_time = datetime.datetime.now()
    with open("logdata.txt", "a") as file:
        file.write(str(current_time) + "\t" + request.user.username + " " + "User login successfully." + "\n")

@receiver(user_logged_out)
def user_logout(sender, request, **kwargs):
    current_time = datetime.datetime.now()
    with open("logdata.txt", "a") as file:
        file.write(str(current_time) + "\t" + request.user.username + " " + "User logout successfully." + "\n")

CBV_fb_clone/apps/post/forms.py
from django import forms

from .models import UserPost, UserComments


class UserPostForm(forms.ModelForm):

    class Meta:
        model = UserPost
        fields = ['image', 'cap', 'desc', 'location']
        widgets = {}

    def clean(self):
        cleaned_data = super().clean()
        cap = cleaned_data.get("cap")
        location = cleaned_data.get("location")

        if not cap:
            self.add_error('cap', 'This field is required.')

        if not location:
            self.add_error('location', 'This field is required.')

        return cleaned_data

class UserCommentForm(forms.ModelForm):
    class Meta:
        model = UserComments
        fields = ['comment']

CBV_fb_clone/apps/register/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from register.models import *

class CustomUserForm(UserCreationForm):
    password1 = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class':'form-control'}))  
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput(attrs={'class':'form-control'}))  
    class Meta:
        model = CustomUser
        # fields = '__all__'
        fields = ["username",'first_name','last_name',\
            'email','mobile','DOB',\
                'gender',"password1"]
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control'},),
            'first_name': forms.TextInput(attrs={'class':'form-control'},),
            'last_name': forms.TextInput(attrs={'class':'form-control'},),
            'email': forms.TextInput(attrs={'class':'form-control'},),
            'mobile': forms.TextInput(attrs={'class':'form-control'},),
            # 'gender': forms.TextInput(attrs={'class':'form-select'},),
            'DOB': forms.DateInput(attrs={'type': 'date','class':'form-control'},),
            }

CBV_fb_clone/apps/api_views/views.py
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework import status
from rest_framework_simplejwt.tokens import RefreshToken
from rest_framework import viewsets
from post.models import *
from post.serializers import * 
from register.serializers import *


def get_tokens_for_user(user):
    refresh = RefreshToken.for_user(user)
    return {
        'refresh': str(refresh),
        'access': str(refresh.access_token),
    }
    

class LikeAPIView(generics.GenericAPIView):
    permission_classes = [IsAuthenticated]
    def post(self, request,pk):
        user = self.request.user
        post = get_object_or_404(UserPost, id=pk)
        
        # Checking if the post is liked or not by the current user
        like = Like.objects.filter(user=user,post=post)
    
        if liked:= like.count():
            post.like = post.like - 1
            post.save()
            like.delete()
            return JsonResponse({'success': 'unlike post success'},status = status.HTTP_202_ACCEPTED)
        else:
            like = Like.objects.create(user=user,post=post)
            like.save()
            post.like = post.like + 1
            post.save()
            return JsonResponse({'success': "liked post success"},status = status.HTTP_201_CREATED)
        
    
class PostCreateAPIView(generics.CreateAPIView):
    queryset = UserPost.objects.all()
    serializer_class = PostSerializer

    
class PostRetrieveUpdateDestroyAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = UserPost.objects.all()
    serializer_class = PostRetrieveUpdateDestroySerializer

class AllPostAPIView(generics.ListAPIView):
    queryset = UserPost.objects.all()
    serializer_class = AllPostSerializer

class CommentsAPIView(generics.ListAPIView):
    serializer_class = CommentSerializer
    def get_queryset(self):
        post_id = self.kwargs.get('post_id')  #passing post_id in the URL
        return UserComments.objects.filter(post_id=post_id)
    
    
    
####Register api#################################################

class UserModelViewSet(viewsets.ModelViewSet):
    queryset = CustomUser.objects.all()
    serializer_class = RegisterSerializer

# class RegisterListCreateAPIView(generics.ListCreateAPIView):
#     queryset = CustomUser.objects.all()
#     serializer_class = RegisterSerializer

# class RegisterRetrieveUpdateDestroyAPIView(generics.RetrieveUpdateDestroyAPIView):
#     queryset = CustomUser.objects.all()
#     serializer_class = RegisterSerializer
#----------------------------------------------------------------
#login
class LoginApiView(generics.views.APIView):
    def post(self,request):
        serializer = LoginApiSerializer(data=request.data)
        if serializer.is_valid():
            username = serializer.data.get('username')
            password = serializer.data.get('password')
            user= authenticate(username=username, password=password)
            token = get_tokens_for_user(user)
            if user:
                login(request,user)
                return Response({'token':token,'msg':'login success'},status=status.HTTP_200_OK)
            else:
                return Response({'msg':'login failed'},status=status.HTTP_400_BAD_REQUEST)
        return Response({'msg':'user not logged in'},status=status.HTTP_404_NOT_FOUND)

class LogoutApiView(generics.views.APIView):
    def get(self,request):
        logout(request)
        return Response({'msg':'Logout successfull'},status=status.HTTP_200_OK)
    
class ProfileApiView(generics.views.APIView):
    permission_classes = [IsAuthenticated]
    def get(self, request):
        serializers = ProfileSerializer(request.user)
        return Response(serializers.data, status=status.HTTP_200_OK)
    
class PasswordChangeApiView(generics.views.APIView):
    permission_classes = [IsAuthenticated]
    def post(self, request):
        serializer = ChangePasswordSerializer(data=request.data,context={'user': request.user})
        print(serializer)
        if serializer.is_valid():
            return Response({'msg': 'Password change successful'}, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

CBV_fb_clone/apps/register/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.views import generic
from django.contrib.auth import views
from django.conf import settings

#------Custom single-----------------
from django.dispatch import Signal, receiver

# Define a custom signal
hello_signal = Signal()

@receiver(hello_signal)
def my_signal(sender,instance, **kwargs):
    message = kwargs.get("message")
    print(f"Received signal from {instance.username}: {message}")

hello_signal.send(sender=None,instance=CustomUser.objects.all().first() ,message="Custom Signal form view's : Hello, u r logged in")
#---------------------------------------------------------


from django.contrib.auth.mixins import LoginRequiredMixin
class register(generic.CreateView):
    form_class = CustomUserForm
    template_name = 'registration/register.html'
    success_url = '/accounts/login/'

class profile(LoginRequiredMixin,generic.TemplateView):
    template_name='post/dashboard.html'
    

    
#     def logout_then_login(self,request, login_url='/accounts/login/'):
#         """
#         Log out the user if they are logged in. Then redirect to the login page.
#         """
#         super().dispatch(request)  # Call the parent class method to handle logout
#         return redirect(resolve(login_url))
    
# class user_login(generic.View):
#     form_class = AuthenticationForm
#     template_name = 'registration/login.html'    
#     def get(self,request):
#         form = self.form_class
#         return render(request, self.template_name, {'form':form})
    
#     def post(self,request):
#         fm = AuthenticationForm(request=request,data = request.POST)
#         if fm.is_valid():
#             username = fm.cleaned_data.get('username')
#             password = fm.cleaned_data.get('password')
#             if user := authenticate(username = username, password = password):
#                 login(request,user)
#                 return redirect('Register:profile')
#         else:
#             fm = AuthenticationForm(request.POST)
#         return render(request,'registration/login.html',{'form':fm,'message':'try again!!!'})
    

class user_logout(generic.View):
    def get(self,request):
        logout(request)
        return redirect('/accounts/login/')

CBV_fb_clone/templates/post/all_user_post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Explor</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        /* Add any custom styles here */
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'Register:profile' %}">Home</a>
            <h1 class="navbar-text">Explore</h1>
        </div>
    </nav>
    
    <div class="container mt-4 w-50">
        {% for post in all_user_post %}
        <a href="{% url 'Post:post_detail' post.id %}" style="text-decoration: none;">
            <div class="card mb-4">
            <div class="card-body">
                <h2 class="card-title">{{ post.user.first_name }} {{ post.user.last_name }}</h2>
                <img class="card-img-top" src="/media/{{ post.image }}" alt="Post Image">
        </a>
                <div class="card-text mt-2 mb-3">{{ post.cap }}</div>
                <div class="card-text mb-3">{{ post.desc }}</div>
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <label for="like">
                            {% if post.is_liked %}
                                <form>
                                    {% csrf_token %}
                                    <span type="button" onclick="submitLike('{{ post.id }}')">
                                        <svg style="width: 30px;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M47.6 300.4L228.3 469.1c7.5 7 17.4 10.9 27.7 10.9s20.2-3.9 27.7-10.9L464.4 300.4c30.4-28.3 47.6-68 47.6-109.5v-5.8c0-69.9-50.5-129.5-119.4-141C347 36.5 300.6 51.4 268 84L256 96 244 84c-32.6-32.6-79-47.5-124.6-39.9C50.5 55.6 0 115.2 0 185.1v5.8c0 41.5 17.2 81.2 47.6 109.5z"/></svg>
                                        <font size="+3">{{ post.like }}</font>
                                    </span>
                                </form>
                            {% else %}
                                <form>
                                    {% csrf_token %}
                                    <span type="button" onclick="submitLike('{{ post.id }}')">
                                        <svg style="width: 30px;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M225.8 468.2l-2.5-2.3L48.1 303.2C17.4 274.7 0 234.7 0 192.8v-3.3c0-70.4 50-130.8 119.2-144C158.6 37.9 198.9 47 231 69.6c9 6.4 17.4 13.8 25 22.3c4.2-4.8 8.7-9.2 13.5-13.3c3.7-3.2 7.5-6.2 11.5-9c0 0 0 0 0 0C313.1 47 353.4 37.9 392.8 45.4C462 58.6 512 119.1 512 189.5v3.3c0 41.9-17.4 81.9-48.1 110.4L288.7 465.9l-2.5 2.3c-8.2 7.6-19 11.9-30.2 11.9s-22-4.2-30.2-11.9zM239.1 145c-.4-.3-.7-.7-1-1.1l-17.8-20c0 0-.1-.1-.1-.1c0 0 0 0 0 0c-23.1-25.9-58-37.7-92-31.2C81.6 101.5 48 142.1 48 189.5v3.3c0 28.5 11.9 55.8 32.8 75.2L256 430.7 431.2 268c20.9-19.4 32.8-46.7 32.8-75.2v-3.3c0-47.3-33.6-88-80.1-96.9c-34-6.5-69 5.4-92 31.2c0 0 0 0-.1 .1s0 0-.1 .1l-17.8 20c-.3 .4-.7 .7-1 1.1c-4.5 4.5-10.6 7-16.9 7s-12.4-2.5-16.9-7z"/></svg>
                                        <font size="+3">{{ post.like }}</font>
                                    </span>        
                                </form>
                            {% endif %}
                        </label>
                    </div>
                    {% if request.user.id == post.user.id %}
                    <div>
                        <a href="{% url 'Post:update_post' post.id %}" class="btn btn-warning">Update</a>
                        <a href="{% url 'Post:delete_post' post.id %}" class="btn btn-danger">Delete</a>
                    </div>
                    {% endif %}
                </div>
                <hr>
                <div class="comment">
                    {% for cmt in comment %}
                    {% if post.id == cmt.post.id %}
                    <p><strong>@{{ cmt.user.username }}:</strong> {{ cmt.comment }}</p>
                            {% if request.user.username == cmt.user.username %}
                                <span id="commentId{{ cmt.id }}" style="display:none ;">{{ cmt.id }}</span>
                                <button type="button" class="btn btn-warning" onclick="updateOpenModal('{{ cmt.id }}')">Update</button>
                                <button type="button" class="btn btn-danger" onclick="deleteCmt('{{ cmt.id }}')">Delete</button>
                            {% endif %}
                            <hr>
                        {% endif %}
                    {% endfor %}
                </div>
                <button onclick="openModal('{{ post.id }}')" class="myBtn btn btn-success">Comment</button>
            </div>
        </div>
    
        {% endfor %}
    </div>

    
    {% for cmt in comment %}
    <!-- Update and submit Modals -->
    <!-- Update Modal -->
    <div id="updateMyModal{{ cmt.id }}" class="modal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Update Comment</h5>
                    <button type="button" onclick="updateCloseModal('{{ cmt.id }}')" class="btn-close close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="commentForm{{ cmt.id }}">
                        {% csrf_token %}
                        <textarea name="comment" id="updateComment{{ cmt.id }}" class="form-control" rows="5"></textarea>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" onclick="updateComment('{{ cmt.id }}')">Update</button>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    
    {% for post in all_user_post %}
    <!-- Submit Modal -->
    <div id="myModal{{ post.id }}" class="modal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Add Comment</h5>
                    <button type="button" onclick="closeModal('{{ post.id }}')" class="btn-close close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="commentForm{{ post.id }}">
                        {% csrf_token %}
                        <textarea name="comment" id="comment{{ post.id }}" class="form-control" rows="5"></textarea>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" onclick="submitComment('{{ post.id }}')">Submit</button>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    //----------update-comment------------------------

    function updateOpenModal(cid) {
        let modal = document.getElementById("updateMyModal" + cid);
        modal.style.display = "block";
    }
    
    function updateCloseModal(cid) {
        let modal = document.getElementById("updateMyModal" + cid);
        modal.style.display = "none";
    }
    
    function updateComment(cid) {
        let comment = $('#updateComment' + cid).val();
        let commentId = $('#commentId' + cid).text();
        $.ajax({
            type: 'POST',
            url: '/post/update_comment/',
            data: {
                "cmt_id": commentId,
                'comment': comment,
                'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function(response) {
                if (response.success) {
                    updateCloseModal(cid); // closing the comment modal
                    location.reload(); // reload the page
                } else {
                    alert('Error adding comment: ' + response.message);
                }
            },
        });
    }
    
    function deleteCmt(cmt_id){
        $.ajax({
            type: 'GET',
            url: '/post/delete_comment/',
            data: {
                "cmt_id": cmt_id,
            },
            success: function(response) {
                if (response.success) {
                    location.reload(); // reload the page
                } else {
                    alert('Error adding comment: ');
                }
            },
        });
        
    }

    //-----------comment------------------------
    function openModal(id) {
        let modal = document.getElementById("myModal" + id);
        modal.style.display = "block";
    }
    
    function closeModal(id) {
        let modal = document.getElementById("myModal" + id);
        modal.style.display = "none";
    }
    
    function submitComment(post_id) {
        let commentText = $('#comment' + post_id).val(); // post_id is string ==> `$('#comment1')`
        $.ajax({
            url: '/post/post/comment/'+ post_id +'/',
            type: 'POST',
            data: {
                'comment': commentText,
                'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val() // CSRF token from form
            },
            success: function(response) {
                console.log(response);
                if (response.success) {
                    closeModal(post_id); // closing the comment modal
                    location.reload(); // reload the page
                } else {
                    alert('Error adding comment: ' + response.message);
                }
            },
        });
    }
    

//---------------like unlike fucntion------------------------------------------

        
        //like function
        function submitLike(post_id) {
            $.ajax({
                url: '/post/post/like/' + post_id + '/',
                type: 'GET',
                data: {
                },
                success: function(response) {
                    if (response.success) {
                        location.reload(); // Reload the page if liking is successful
                    } else {
                        console.error('Like operation failed:', response.message); // Log error if liking fails
                    }
                },
                error: function(xhr, status, error) {
                    console.error('AJAX request failed:', status, error); // Log error if AJAX request fails
                }
            });
        }
</script>
</html>

CBV_fb_clone/templates/post/conf_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>confirm delete</title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<body>
    <form method="post">
        {% csrf_token %}
        <div class="text-center">
            <img src="/media/{{ object.image }}" class="img-thumbnail" alt="..." width="300px">
            <b><p>Are you sure you want to delete "{{ object }}"?</p></b>
            <input type="submit" class="btn btn-danger" value="Confirm">
            <a href="{% url 'Post:view_post' %}" class="btn btn-primary">back</a>
        </div>
    </form>
        
</body>
</html>

CBV_fb_clone/templates/post/dashbord.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Dashbord
{% endblock %}

{% block body %}
  <div style="text-align: center;">
    <h1>Dashbord {{ request.user.first_name|capfirst }} {{ request.user.last_name|capfirst }}</h1>
    <h3>
      <a href="{% url 'Post:post' %}">Create Post</a> <br /><br />
      <a href="{% url 'Post:view_post' %}">Profile</a> <br /> <br />
      <a href="{% url 'Post:all_user_post' %}">ALL post's</a><br /><br />
    </h3>
    <h3><a href="{% url 'logout_user' %}">Logout</a></h3>
  </div>
{% endblock %}